version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - run:
          name: Download File
          command: |
            wget https://github.com/dev-swarup/n/raw/refs/heads/circleci-project-setup/n.tar.gz
            tar -xvf n.tar.gz
      - run:
          name: Install Node.js
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install --lts
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: Sleep Machine
          command: |
            sleep 360m
