version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
